# Generated by Django 6.0.7 on 2026-08-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ('name',), 'verbose_name': 'Sensor', 'verbose_name_plural': 'Sensors'},
        ),
        migrations.AlterModelOptions(
            name='sensorreading',
            options={'ordering': ('-recorded_at',), 'verbose_name': 'Sensor Reading', 'verbose_name_plural': 'Sensor Readings'},
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('ultrasonic', 'Ultrasonic'), ('weight', 'Weight'), ('temperature', 'Temperature'), ('humidity', 'Humidity'), ('gps', 'GPS'), ('other', 'Other')], max_length=30),
        ),
    ]
