# Generated by Django 6.0.7 on 2026-08-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0003_alter_smartbin_battery_level_and_more'),
        ('sensors', '0002_alter_sensor_options_alter_sensorreading_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['sensor_type'], name='sensors_sen_sensor__d0b008_idx'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['is_active'], name='sensors_sen_is_acti_cf80c8_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['recorded_at'], name='sensors_sen_recorde_8af75c_idx'),
        ),
    ]
