# Generated by Django 6.0.7 on 2026-08-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('first_name', 'last_name'), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('organization_admin', 'Organization Admin'), ('facility_manager', 'Facility Manager'), ('supervisor', 'Supervisor'), ('operator', 'Operator'), ('driver', 'Driver'), ('technician', 'Technician'), ('viewer', 'Viewer')], default='viewer', max_length=30),
        ),
    ]
