
from django.db.models import QuerySet
from apps.accounts.models import User
from .models import Report
import environ

def get_reports() -> QuerySet[Report]:
    """
    Return all non-deleted reports.
    """
    return (
        Report.objects
        .filter(is_deleted=False)
        .select_related("generated_by")
    )


def get_report(
    report_id,
) -> Report | None:
    """
    Return a single non-deleted report.
    """
    return (
        get_reports()
        .filter(id=report_id)
        .first()
    )


def get_user_reports(
    user: User,
) -> QuerySet[Report]:
    """
    Return reports generated by the given user.
    """
    return (
        get_reports()
        .filter(generated_by=user)
    )


def get_organization_reports(
    user: User,
) -> QuerySet[Report]:
    """
    Return reports belonging to users
    within the requesting user's organization.
    """
    if not user.organization_id:
        return get_reports().none()

    return (
        get_reports()
        .filter(
            generated_by__organization_id=user.organization_id
        )
    )


def get_facility_reports(
    user: User,
) -> QuerySet[Report]:
    """
    Return reports generated by users
    within the requesting user's facility.
    """
    if not user.facility_id:
        return get_reports().none()

    return (
        get_reports()
        .filter(
            generated_by__facility_id=user.facility_id
        )
    )


def get_reports_by_type(
    report_type: str,
) -> QuerySet[Report]:
    """
    Return reports of a specific type.
    """
    return (
        get_reports()
        .filter(report_type=report_type)
    )


def get_reports_by_status(
    status: str,
) -> QuerySet[Report]:
    """
    Return reports with a specific status.
    """
    return (
        get_reports()
        .filter(status=status)
    )


def get_recent_reports(
    limit: int = 10,
) -> QuerySet[Report]:
    """
    Return the most recently created reports.
    """
    return get_reports()[:limit]