# Generated by Django 6.0.7 on 2026-08-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionvehicle',
            options={'ordering': ['registration_number'], 'verbose_name': 'Collection Vehicle', 'verbose_name_plural': 'Collection Vehicles'},
        ),
        migrations.AlterField(
            model_name='collectionvehicle',
            name='registration_number',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
