# Generated by Django 6.0.7 on 2026-08-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0003_alter_smartbin_battery_level_and_more'),
        ('operations', '0002_alter_collectionvehicle_options_and_more'),
        ('organizations', '0004_alter_facility_options_alter_zone_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collectionrecord',
            index=models.Index(fields=['collected_at'], name='operations__collect_a79715_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionroute',
            index=models.Index(fields=['is_active'], name='operations__is_acti_1c6aba_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionschedule',
            index=models.Index(fields=['scheduled_date'], name='operations__schedul_4f12d9_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionschedule',
            index=models.Index(fields=['status'], name='operations__status_cb8f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionvehicle',
            index=models.Index(fields=['status'], name='operations__status_343555_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionvehicle',
            index=models.Index(fields=['is_active'], name='operations__is_acti_60354b_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['is_active'], name='operations__is_acti_1ed9cc_idx'),
        ),
    ]
