# Generated by Django 6.0.7 on 2026-08-03 07:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartBin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('capacity_liters', models.PositiveIntegerField(default=240)),
                ('fill_level', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('battery_level', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='organizations.zone')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('alert_type', models.CharField(choices=[('bin_full', 'Bin Full'), ('battery_low', 'Battery Low'), ('sensor_offline', 'Sensor Offline'), ('fire', 'Fire'), ('tamper', 'Tamper'), ('general', 'General')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('smart_bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='bins.smartbin')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='smartbin',
            constraint=models.UniqueConstraint(fields=('zone', 'code'), name='unique_bin_code_per_zone'),
        ),
    ]
