# Generated by Django 6.0.7 on 2026-08-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ('-triggered_at',)},
        ),
        migrations.AlterModelOptions(
            name='smartbin',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='smartbin',
            name='status',
            field=models.CharField(choices=[('empty', 'Empty'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('full', 'Full'), ('offline', 'Offline')], default='empty', max_length=20),
        ),
    ]
