# Generated by Django 6.0.7 on 2026-08-06 03:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0002_alter_alert_options_alter_smartbin_options_and_more'),
        ('organizations', '0004_alter_facility_options_alter_zone_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartbin',
            name='battery_level',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='smartbin',
            name='fill_level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status'], name='bins_alert_status_0fe25c_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity'], name='bins_alert_severit_319b98_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['triggered_at'], name='bins_alert_trigger_57f92f_idx'),
        ),
        migrations.AddIndex(
            model_name='smartbin',
            index=models.Index(fields=['status'], name='bins_smartb_status_586f41_idx'),
        ),
        migrations.AddIndex(
            model_name='smartbin',
            index=models.Index(fields=['is_active'], name='bins_smartb_is_acti_9b0a82_idx'),
        ),
    ]
