# Generated by Django 6.0.7 on 2026-08-03 11:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPISnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('total_bins', models.PositiveIntegerField(default=0)),
                ('active_bins', models.PositiveIntegerField(default=0)),
                ('collections_completed', models.PositiveIntegerField(default=0)),
                ('waste_collected_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_fill_level', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('snapshot_date', models.DateField()),
            ],
            options={
                'verbose_name': 'KPI Snapshot',
                'verbose_name_plural': 'KPI Snapshots',
                'ordering': ['-snapshot_date'],
            },
        ),
    ]
