# Generated by Django 6.0.7 on 2026-08-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('name',), 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AddField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(choices=[('university', 'University'), ('hospital', 'Hospital'), ('market', 'Market'), ('office', 'Office'), ('residential', 'Residential'), ('industrial', 'Industrial'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
