# Generated by Django 6.0.7 on 2026-08-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_facility_options_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(choices=[('university', 'University'), ('hospital', 'Hospital'), ('market', 'Market'), ('office', 'Office'), ('residential', 'Residential'), ('industrial', 'Industrial'), ('other', 'Other')], default='university', max_length=30),
        ),
    ]
