# Generated by Django 6.0.7 on 2026-08-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='is_successful',
            field=models.BooleanField(default=True),
        ),
    ]
